- name: Setup local condor(LRMS) collector
  hosts: lrms
  vars_files:
    - vars/virtualbox_environ.yml
  roles:
    - role: ansible-htcondor
      condor_daemon_list: "MASTER, COLLECTOR,NEGOTIATOR"
- name: Setup condor submitter
  hosts: condor_ce
  vars_files:
    - vars/virtualbox_environ.yml
  roles:
    - role: ansible-htcondor
      condor_daemon_list: "MASTER, SCHEDD"
- name: Setup local condor Workernodes
  hosts: condor_wn
  vars_files:
    - vars/virtualbox_environ.yml
  roles:
    - role: ansible-htcondor
      condor_daemon_list: "MASTER, STARTD"
- name: Fix NIC to use internal network
  hosts: all
  vars:
    ipinfo:
      - { name: "node0", ip: "192.168.10.3" }
      - { name: "node1", ip: "192.168.10.4" }
      - { name: "node2", ip: "192.168.10.5" }
      - { name: "node3", ip: "192.168.10.6" }
  tasks:
    - copy: 
        dest: /etc/condor/config.d/03-private.conf 
        content: "BIND_ALL_INTERFACES = FALSE\nNETWORK_INTERFACE = {{ item.ip }}\n" 
      when: 
        - "ansible_hostname == item.name"
      with_items:
        - "{{ ipinfo }}"
      notify: restart_condor
  handlers: 
    - name: restart_condor
      service: 
        name: condor
        state: restarted
    - name: restart_condorce
      service: 
        name: condor-ce
        state: restarted

